### ISSUE TITLE
Not recognising Chauffeured Mechano-Hog!

### ISSUE THREAD

**Issue by Mindlessgalaxy** [Bestride/BeStride#102]
Not recognising Chauffeured Mechano-Hog mount on horde so unable to select it as a random mount,

I have put both ID's for Horde and Alliance versions below for you:

Mount ID for the Horde Version:  179244
Mount ID for the Alliance Version:  179245

Not sure if working for Alliance at all, as haven't tried as yet, although I assume it must be as you have addressed this issue previously and I only got the mount yesterday through the heirloom achieve https://www.wowhead.com/spell=179244/summon-chauffeur 

Anywhere in game doesn't work or is not seen on list to select on EN-US client.

BeStride version:  1.0.18
WoW version:  8.1.0.28833

How can we reproduce it.  Please be specific:

If you open up the config you are unable to find this mount at all and therefore unable to select it from the mounts list as a random mount.  Please do not confuse this with the other Chauffeured Mecho Hog https://www.wowhead.com/item=41508/mechano-hog this is a different mount and is easily confused with the achieve one.

Just so you are aware I think Blizzard in their great wisdom have changed the Item ID for this item,  I have found a few different item ID's for this mount and think may be what the problem maybe.  The addon I have that shows in game ID's give the ID's correctly that I need, although I am unable to change it within your addon as I have no idea how to, sorry.  I have put a link above with the correct ID numbers to hopefully help and of course this is not urgent at all, just a little annoyance that I would strongly suggest is to do with Blizzard changes to the achievement and the way we receive the item has also now changed as well.  Will check with one of my Alliance toons later and if you do not hear back from me the fault is also with Alliance as well.

I hope you have a fantastic Christmas and that you also are on break still enjoying and relaxing with the family.  Happy New Year to you and your family as well and I hope it is a great one for you all :),

All the best,

Mindlessgalaxy.

**Comment by DanSheps** [comment]
This should be fixed
