### ISSUE TITLE
Support for Nazjatar/Mechagon

### ISSUE THREAD

**Issue by Debuggernaut** [Bestride/BeStride#107]
I hacked my local copy of BeStride to add Nazjatar into BeStride_Constants like so:

line 138, in:
 		Flight = {
			Restricted = {
				Worlds = {
				},
				Continents = {

					[1355] = { --Nazjatar
						requires = 281576,
					},

but I'm not sure if I put it in the right spot, and I don't have the ID for Mechagon handy, so I didn't want to send out a crappy pull request

**Comment by Daeymien** [comment]
The "requires" would be 233368 for BFA pathfinder Rank 2, allowing flying.

**Comment by DanSheps** [comment]
@Daeymien Why couldn't you do a PR?

**Comment by DanSheps** [comment]
Merged in #110

**Comment by Debuggernaut** [comment]
ah, he probably just doesn't have git set up on his home computer or something

I hadn't ever done any github pull requests either, so it was a learning experience, haha.  At all my jobs I've done all my work under layer after layer of NDAs, so even when I worked on open source stuff I wasn't allowed to send out patches

Thanks for merging the PRs!

**Comment by Daeymien** [comment]
@DanSheps 
> @Daeymien Why couldn't you do a PR?

> ah, he probably just doesn't have git set up on his home computer or something

This, mostly. Travelling and on tablet. Git clients for Android are horrendous.

**Comment by DanSheps** [comment]
Fair, just wanted to make sure it wasn't anything broken on my end.
