### ISSUE TITLE
Change druid forms in combat not working

### ISSUE THREAD

**Issue by penguinsane** [Bestride/BeStride#114]
I use the option to shift into travel form or cat form depending on indoors/outdoors, but it no longer works in combat. Is this something that can be fixed, or something that was changed on Blizzard's end?

**Comment by DanSheps** [comment]
You need to have traveltotravel enabled.  However, I will look at the code and see if there is a way todo this.

**Comment by penguinsane** [comment]
> You need to have traveltotravel enabled.

Do you mean the option for "Druid: When in combat, shift from Travel or Aquatic form directly back to that form"? I do have that enabled. 

The only class option that I do not have enabled is "Druid: Prioritize using Flight Form over a regular mount even when not moving."

**Comment by DanSheps** [comment]
I tested this with a dummy in IF, and it does set the right form.  I will do some more testing.
