### ISSUE TITLE
Key Binding 

### ISSUE THREAD

**Issue by WeirDave** [Bestride/BeStride#122]
### Environment
* BeStride version: BeStride-v1.0.21
* WoW version: 9.01

This is a report and a request for assistance. I got the add on from Twitch. It stated:
BeStride is a mount manager that has the following functionality

All in one mount button - **_Where is this button?_**

I also tried to use the keybinds. I must have done something wrong and I can't fix it. Any help would be appreciated. Also any suggestions on what keys to use would be great too!
Allows additional keybinds for overriding functionality. _**See below**_

### Steps to reproduce
I bound the key to my middle mouse button for the "Mount Button" It doesn't seem to work. I tried reassigning it to something else and it doesn't seem to save. I have tried Alt and number. Control and numbers even control shift and number key numbers. I also tried uninstalling and reinstalling but it is stuck on "Button3" when using that it says "[Debug]Fatal:Unmatch (settings.mopuint.emptyrandom)

### Expected Behaviour
For the keybinds to operate the program

### Actual Behaviour
Nothing

### Bestride Variables

###Screenshots

{EDIT} I went back in after I uninstalled and my binds were set to "control 1-4" which now seems to work. The next day they are broken again

**Comment by DanSheps** [comment]
@WeirDave Are you still having issues?  If so, can you delete your Bestride.lua and try to reinitialize it?

**Comment by WeirDave** [comment]
I am I actually uninstalled it because it wasn't working for me. can you tell me where that file is located in order to delete it? And I'll give that a shot. I really do want it to work.

**Comment by DanSheps** [comment]
It is in your WTF\Account\<Account>\SavedVariables\Bestride.lua

**Comment by DanSheps** [comment]
Also please reset your keybindings (only these specific ones if you need) before re-enabling it

**Comment by WeirDave** [comment]
Thank you. Also what keybinds do you recommend?

**Comment by DanSheps** [comment]
I use middle mouse button.  Ctrl middle mouse for Force I think.

**Comment by WeirDave** [comment]
> It is in your WTF\Account<Account>\SavedVariables\Bestride.lua

Unable to locate this. I found my WOW folder...

**Comment by DanSheps** [comment]
It should be in:

C:\Program Files (x86)\World of Warcraft\_retail_\WTF

If you have deleted anything under addons you have broken the addon and will need to reinstall

**Comment by WeirDave** [comment]
I have uninstalled and reinstalled. When I uninstalled I exited the game uninstalled saw it delete the directory. Reinstalled and logged back in only to find that the key bindings were the same. I have treid using the escape to clear the bindings. I exit the GUI and go back in and they are not cleared.

**Comment by DanSheps** [comment]
I see the keybinds are not clearing.

For support, join the discord, I am going to close this and open a new issue for troubleshooting the keybind issue.
