### ISSUE TITLE
Option to mimic your targets mount

### ISSUE THREAD

**Issue by Capfrey** [Bestride/BeStride#128]
Was wondering if there is any chance that there could be an option where the addon tries to mimic your targets mount. So if your target is using invincible, the addon will mount invincible as well if you have it in your collection and click the mount up button.
Would be an awesome feature for mount offs and generally just a fun option.

**Comment by DanSheps** [comment]
I don't think this is something we are going to persue

**Comment by DanSheps** [comment]
Merged in master
