### ISSUE TITLE
Reven Lord Mount not found

### ISSUE THREAD

**Issue by Djurkwhad** [Bestride/BeStride#183]
### WoW Version

WotLK (3.4.0)

### Bestride Version

2.0.4 

### Steps to Reproduce

Reven Lord mount is not in the DB

[11:16] Mount not in DB: 
[11:16] 	Name: Raven Lord 
[11:16] 	Mount ID:23408 
[11:16] 	Spell ID:41252 

### Observed Behavior

Recently obtained Raven Lord mount, but it is not detected by the addon.

**Comment by sfjuocekr** [comment]
Yup, this one needs to be added!

**Comment by coreymyers** [comment]
Yes please fix this.
