### ISSUE TITLE
Sea Turtle mount missing under Swimming tab

### ISSUE THREAD

**Issue by chon379** [Bestride/BeStride#186]
### WoW Version

WotLK (3.4.0)

### Bestride Version

3.4.0

### Steps to Reproduce

1. Open Bestride addon
2. Click on Swimming tab under Mounts
3. Sea Turtle missing
![image](https://user-images.githubusercontent.com/112575457/197252103-a89659b0-bc1e-4611-b99f-73c248b75de9.png)

### Observed Behavior

No errors reported, Sea Turtle mount is just missing.

**Comment by davidgrundstrom** [comment]
To add to this: It does show up as a ground mount instead

**Comment by davidgrundstrom** [comment]
I opened a PR to fix this: https://github.com/Bestride/BeStride/pull/199
