### ISSUE TITLE
Dismount in combat

### ISSUE THREAD

**Issue by Nimmsis** [Bestride/BeStride#193]
### WoW Version

WotLK (3.4.0)

### Bestride Version

2.0.4

### Steps to Reproduce

Pressing the mount/dismount button when in combat

### Observed Behavior

does not dismount the character. have to attack the target to dismount.

**Comment by DanSheps** [comment]
Need a little more information then this.

Were you flying?
What class?
What mount?

**Comment by Nimmsis** [comment]
Class: Warlock
Mounts: All mounts (Warlock mounts, Flying Carpet, flying mounts, Non Flying mounts)

i was both flying and on the ground.
Not locked to any zone, cant dismount in northrend, kalimdor och outlands.
Disabled all other Addons to make sure there is not a conflict
note, my 60 rogue can dismount in combat (only have a 100% undead horse).
