### ISSUE TITLE
Missing Mounts

### ISSUE THREAD

**Issue by Lisann76** [Bestride/BeStride#216]
### WoW Version

Retail (9.2.5)

### Bestride Version

2.0.6

### Steps to Reproduce

Following mounts might need to be added:
Kua'fon

[https://www.wowhead.com/spell=267270/kuafon](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowhead.com%252fspell%253d267270%252fkuafon)

and
Otterworldly Ottuk Carrier

[https://www.wowhead.com/spell=376912/otterworldly-ottuk-carrier](https://www.curseforge.com/linkout?remoteUrl=https%253a%252f%252fwww.wowhead.com%252fspell%253d376912%252fotterworldly-ottuk-carrier)

Thank you.

### Observed Behavior

They are missing in the lists.

**Comment by DanSheps** [comment]
Are these mounts properly appearing with the latest version?

**Comment by Lisann76** [comment]
No, unfortunately not at all. (german client)
