### ISSUE TITLE
Error trying to use mount

### ISSUE THREAD

**Issue by Tednik** [Bestride/BeStride#226]
### WoW Version

Retail (10.0.2)

### Bestride Version

2.0.9

### Steps to Reproduce

Go to Draenor in Spires of Arak try to use mount keybind

### Observed Behavior

20x ...rfaceBeStride/Versions/Common/logic.zone.lua:82: attempt to index local 'micro' (a nil value)
[string "@BeStride/Versions/Common/logic.zone.lua"]:82: in function `IsSpecialZone'
[string "@BeStride/Versions/Common/mount.lua"]:51: in function `Regular'
[string "@BeStride/Versions/Common/BeStride_ActionButton.lua"]:45: in function `PreClick'
[string "@BeStride/Versions/Common/BeStride_ActionButton.lua"]:26: in function <...s/BeStride/Versions/Common/BeStride_ActionButton.lua:26>

Locals:
self = <table> {
 DruidCanCat = <function> defined @BeStride/Versions/Common/logic.class.lua:302
 IsPaladin = <function> defined @BeStride/Versions/Common/logic.class.lua:55
 modules = <table> {
 }
 EvokerCanHover = <function> defined @BeStride/Versions/Common/logic.class.lua:466
 AddCommonMount = <function> defined @BeStride/Versions/Common/mount.table.lua:25
 IsSpecialZone = <function> defined @BeStride/Versions/Common/logic.zone.lua:75
 MonkCanTorpedo = <function> defined @BeStride/Versions/Common/logic.class.lua:411
 NeedToRepair = <function> defined @BeStride/Versions/Common/logic.special.lua:20
 IsMainline = <function> defined @BeStride/Versions/Mainline/bestride.lua:9
 SetDefaultModulePrototype = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:405
 DruidCanTravel = <function> defined @BeStride/Versions/Common/logic.class.lua:292
 IsDemonHunterAndSpecial = <function> defined @BeStride/Versions/Common/logic.class.lua:126
 IsEnabled = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:447
 DruidTravelToTravel = <function> defined @BeStride/Versions/Common/logic.class.lua:574
 CanBroom = <function> defined @BeStride/Versions/Common/logic.mounts.lua:1
 IsEvokerAndSpecial = <function> defined @BeStride/Versions/Common/logic.class.lua:100
 RegisterMessage = <function> defined @Ace3/CallbackHandler-1.0/CallbackHandler-1.0.lua:85
 PaladinCanDivineSteed = <function> defined @BeStride/Versions/Common/logic.class.lua:431
 IsShamanAndSpecial = <function> defined @BeStride/Versions/Common/logic.class.lua:257
 IsRepairable = <function> defined @BeStride/Versions/Common/logic.special.lua:39
 db = <table> {
 }
 MageBlink = <function> defined @BeStride/Versions/Common/logic.class.lua:635
 CreateActionButton = <function> defined @BeStride/Versions/Common/BeStride_ActionButton.lua:7
 DemonHunterCanGlide = <function> defined @BeStride/Versions/Common/logic.class.lua:350
 SetEnabledState = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:420
 DeathKnightWraithWalk = <function> defined @BeStride/Versions/Common/logic.class.lua:493
 SpecialZone = <function> defined @BeStride/Versions/Common/mounting.zone.lua:1
 DBSetMount = <function> defined @BeStride/Versions/Common/settings.lua:56
 RogueCanSprint = <function> defined @BeStride/Versions/Common/logic.class.lua:478
 Evoker = <function> defined @BeStride/Versions/Common/mounting.class.lua:121
 IsEvoker = <function> defined @BeStride/Versions/Common/logic.class.lua:91
 MageCanSlowFall = <function> defined @BeStride/Versions/Common/logic.class.lua:378
 IsMonkAndSpecial = <function> defined @BeStride/Versions/Common/logic.class.lua:195
 RogueSprint = <function> defined @BeStride/Versions/Common/logic.class.lua:727
 Combat = <function> defined @BeStride/Versions/Common/mount.lua:228
 OnInitialize = <function> defined @BeStride/Versions/Common/bestride.lua:1
 NewModule = <function> defined @Ace3/AceAddon-3.0/AceAddon-3.0.lua:231
 GroundMountButton = <function> defined @BeStride/Versions/Common/mount.lua:124
 UpdateOverrideBindings = <function> defined @BeStride/Versions/Common/bestride.lua:75
 isZoneMount = <function> defined @BeStride/Versions/Mainline/logic.lua:11
 EventNewMount = <function> defined @BeStride/Versions/Common/BeStride_Events.lua:1
 IsPaladinAndSpecial = <function> defined @BeStride/Versions/Common/logic.class.lua:213
 IsMage = <function> defined @BeStride/Versions/Common/log

**Comment by Lisann76** [comment]
I can confirm the error:

Message: ...rface/AddOns/BeStride/Versions/Common/logic.zone.lua:82: attempt to index local 'micro' (a nil value)
Time: Mon Nov 28 19:23:32 2022
Count: 10
Stack: ...rface/AddOns/BeStride/Versions/Common/logic.zone.lua:82: attempt to index local 'micro' (a nil value)
[string "@Interface/AddOns/BeStride/Versions/Common/logic.zone.lua"]:82: in function `IsSpecialZone'
[string "@Interface/AddOns/BeStride/Versions/Common/mount.lua"]:51: in function `Regular'
[string "@Interface/AddOns/BeStride/Versions/Common/BeStride_ActionButton.lua"]:45: in function `PreClick'
[string "@Interface/AddOns/BeStride/Versions/Common/BeStride_ActionButton.lua"]:26: in function <...s/BeStride/Versions/Common/BeStride_ActionButton.lua:26>
[string "=[C]"]: in function `Click'
[string "@Interface/FrameXML/ChatFrame.lua"]:1617: in function `?'
[string "@Interface/FrameXML/ChatFrame.lua"]:5204: in function <Interface/FrameXML/ChatFrame.lua:5170>
[string "=[C]"]: ?
[string "=[C]"]: in function `ChatEdit_ParseText'
[string "@Interface/FrameXML/ChatFrame.lua"]:4888: in function <Interface/FrameXML/ChatFrame.lua:4887>
[string "=[C]"]: in function `ChatEdit_SendText'
[string "@Interface/FrameXML/ChatFrame.lua"]:3132: in function <Interface/FrameXML/ChatFrame.lua:3125>
...
[string "=[C]"]: in function `UseAction'
[string "@Interface/FrameXML/SecureTemplates.lua"]:364: in function `handler'
[string "@Interface/FrameXML/SecureTemplates.lua"]:690: in function <Interface/FrameXML/SecureTemplates.lua:672>
[string "@Interface/FrameXML/SecureTemplates.lua"]:704: in function <Interface/FrameXML/SecureTemplates.lua:697>
[string "@Interface/FrameXML/SecureTemplates.lua"]:746: in function <Interface/FrameXML/SecureTemplates.lua:730>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:266: in function <Interface/FrameXML/SecureHandlers.lua:263>
[string "=[C]"]: ?
[string "@Interface/FrameXML/SecureHandlers.lua"]:296: in function <Interface/FrameXML/SecureHandlers.lua:279>
[string "=(tail call)"]: ?

Locals: self = <table> {
 DruidCanCat = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:302
 IsPaladin = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:55
 modules = <table> {
 }
 EvokerCanHover = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:466
 AddCommonMount = <function> defined @Interface/AddOns/BeStride/Versions/Common/mount.table.lua:25
 IsSpecialZone = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.zone.lua:75
 MonkCanTorpedo = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:411
 NeedToRepair = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.special.lua:20
 IsMainline = <function> defined @Interface/AddOns/BeStride/Versions/Mainline/bestride.lua:9
 SetDefaultModulePrototype = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:405
 DruidCanTravel = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:292
 IsDemonHunterAndSpecial = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:126
 IsEnabled = <function> defined @Interface/AddOns/!KalielsTracker/Libs/AceAddon-3.0/AceAddon-3.0.lua:447
 DruidTravelToTravel = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:574
 CanBroom = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.mounts.lua:1
 IsEvokerAndSpecial = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:100
 RegisterMessage = <function> defined @Interface/AddOns/LibSharedMedia-3.0/CallbackHandler-1.0/CallbackHandler-1.0.lua:90
 PaladinCanDivineSteed = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:431
 IsShamanAndSpecial = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.class.lua:257
 IsRepairable = <function> defined @Interface/AddOns/BeStride/Versions/Common/logic.special.lua:39

**Comment by madhandennis** [comment]
Until a patch for this is released (https://github.com/Bestride/BeStride/pull/237), you can manually edit the code and fix this temporarily if you want.
