### ISSUE TITLE
Missing Mounts 10.x  (nov 27th 2022)

### ISSUE THREAD

**Issue by Prov1dence-I** [Bestride/BeStride#227]
### WoW Version

Retail (9.2.5)

### Bestride Version

2.0.9

### Steps to Reproduce

1. Acquire otterworldly ottuk carrier, any aurelid, or  unsuccessful prototype feeltpod
2. check mount lists
3. When leveling a dracthyr and getting their racial mounts and adding them to your list the mod will return an error in chat log on which mounts arent added that youve collected with what i assume are the mount codes leading. I did not get a screenshot of this 

### Observed Behavior

Mounts not added on list and cant be ticked to add to the random list

**Comment by DanSheps** [comment]
If you reload or log off and on, do they appear in the list then?

**Comment by DanSheps** [comment]
Also, this should not appear in Retail, it should be loading a completely different method for adding mounts compared to Classic/Wrath.

**Comment by Prov1dence-I** [comment]
Negative on the relogging/reloading. and I hadnt ever seen that behavior before leveling the dracthyr and adding their mounts, That was on 11/23/22. I knew a few mounts were missing firstly the unsuccessful prototype fleetpod, but it moves at an extremely reduced speed so it wasnt really an issue and thought that it might have been intentional. I forget exactly when I added that mount but its been a few months. I wish I had taken a screen shot at the time and im sorry about that. Hopefully someone else will be able to replicate that and get a screenshot

**Comment by DanSheps** [comment]
So this isn't something you experienced recently then?

**Comment by Prov1dence-I** [comment]
Correct, I guess it started during the zerith mortis patch, havent ever had a problem before. It wasnt pressing of course and i know you're a busy person as am I so i never published an issue about it, but I do thank you for your work on the project more than you know

**Comment by DanSheps** [comment]
It looks like these are tied to a few new mountTypeIds and those should be fixed in the next release
