### ISSUE TITLE
Can't Dismount while flying

### ISSUE THREAD

**Issue by DanielEMoore** [Bestride/BeStride#238]
### WoW Version

Retail (9.2.5)

### Bestride Version

2.0.10

### Steps to Reproduce

1. I cant dismount while flying (Dragon flying)
2. The options is set to false.
3. ![image](https://user-images.githubusercontent.com/7445821/209206100-7e717479-7e81-4a90-9278-1feed13bf084.png)

### Observed Behavior

I would like to dismount while flying.

**Comment by RAtwood90** [comment]
It's working for me.
