### ISSUE TITLE
Dragonflight Dragonriding

### ISSUE THREAD

**Issue by Lisann76** [Bestride/BeStride#239]
### WoW Version

Retail (9.2.5)

### Bestride version

2.0.10

### Proposed functionality

WoW Retail 10.0.2

Hello, it would be really great if you could prioritize the new riding dragons on the Dragon Islands.

**Comment by DanSheps** [comment]
You mean to choose a dragonriding mount over a normal?  I don't think this is relevant anymore as all flying are dragonriding I think.
