### ISSUE TITLE
You FORGOT the ALLMIGTHY Warlocks xD

### ISSUE THREAD

**Issue by RAtwood90** [Bestride/BeStride#248]
### WoW Version

Retail (9.2.5)

### Bestride Version

Latest

### Steps to Reproduce

https://www.wowhead.com/spell=111400/burning-rush

Is missing in your Table Mate. :(

Sad Warlock typing here :P 

Good Addon anyway thanks for that!

### Observed Behavior

See above.

**Comment by DanSheps** [comment]
Thanks!  I don't play a lot of retail anymore, I will try and get this added.  Would you be willing to test?

**Comment by RAtwood90** [comment]
> Thanks! I don't play a lot of retail anymore, I will try and get this added. Would you be willing to test?

Sure Mate. Then i find more Spells like this i will let you know.

**Comment by RAtwood90** [comment]
> Thanks! I don't play a lot of retail anymore, I will try and get this added. Would you be willing to test?

I did some work for you may it Helps. It's still not working but it's showing up in the Options with "Settings.Classes.Warlock.BurningRush".

May it's just to be adjusted.
[BeStride.zip](https://github.com/Bestride/BeStride/files/11547659/BeStride.zip)

Also fixed an Mistake by you you had in one File two Times "Priest Spells" as Hover one of them was for the Paladin.

**Comment by RAtwood90** [comment]
@DanSheps Hey Bro! Just wanna ask how the Progress is?

May we can met together on Discord or something?

Got some adjustments too for other Classes. After playing them. Would be nice :)

RAtwood90 is my Discord Addy.
