### ISSUE TITLE
Error with OPie integration

### ISSUE THREAD

**Issue by BlartVersenwald** [Bestride/BeStride#257]
### WoW Version

Retail (9.2.5)

### Bestride Version

2.0.14

### Steps to Reproduce

One time error on init

### Observed Behavior

Message: Interface/AddOns/BeStride/Versions/Common/opie.lua:39: desc[4].sliceToken value is missing, invalid, or not [globally] unique (boolean)
Time: Fri Sep  1 11:58:53 2023
Count: 1
Stack: Interface/AddOns/BeStride/Versions/Common/opie.lua:39: desc[4].sliceToken value is missing, invalid, or not [globally] unique (boolean)
[string "=[C]"]: in function `error'
[string "@Interface/AddOns/OPie/OPieCore.lua"]:1421: in function `FutureDeprecationError'
[string "@Interface/AddOns/OPie/CustomRings.lua"]:335: in function <Interface/AddOns/OPie/CustomRings.lua:305>
[string "@Interface/AddOns/OPie/CustomRings.lua"]:434: in function <Interface/AddOns/OPie/CustomRings.lua:431>
[string "@Interface/AddOns/OPie/CustomRings.lua"]:462: in function `AddDefaultRing'
[string "@Interface/AddOns/BeStride/Versions/Common/opie.lua"]:39: in function <Interface/AddOns/BeStride/Versions/Common/opie.lua:6>
[string "@Interface/AddOns/BeStride/Versions/Common/opie.lua"]:50: in function <Interface/AddOns/BeStride/Versions/Common/opie.lua:47>

Locals: (*temporary) = "desc[4].sliceToken value is missing, invalid, or not [globally] unique (boolean)"

**Comment by TylerR909** [comment]
I'll check this out.
