### ISSUE TITLE
Dark Phoenix mount not added (Cataclysm)

### ISSUE THREAD

**Issue by Radiskillz** [Bestride/BeStride#276]
### WoW Version

WotLK (3.4.0)

### Bestride Version

2.0.20

### Steps to Reproduce

1. Learn the Dark Phoenix mount (itemid 63125, spellid 88990)
2. type /br
3. check the "flying" tab

### Observed Behavior

I'm not able to select the dark phoenix mount in wow cataclysm classic.
I've tried relogging and reloading.
when using the /br reload command i get the message:
Dark Phoenix:1890:88990:229
Not Adding MountDark Phoenix Id: 1890 SpellId: 88990"

**Comment by Dooplis** [comment]
Sad this is what I came here for too, aswell as Abyssal seahorse, guess im not using this addon

**Comment by PirateKain** [comment]
Ya, there are a lot of missing mounts with this addon
