### ISSUE TITLE
Fatal: Unmatch CATA 4.4.1

### ISSUE THREAD

**Issue by Brum8842** [Bestride/BeStride#294]
### WoW Version

WotLK (3.4.0)

### Bestride Version

2.0.23

### Steps to Reproduce

1. Press keybind
2. Open BeStride Options
3. Check each Mount Tabs

### Observed Behavior

When pressing my keybind I get this wall of text
![image](https://github.com/user-attachments/assets/ed366740-9004-405a-badf-3c6ee8f2124d)

When I open the BeStride Options I get this
![image](https://github.com/user-attachments/assets/302a1136-eb1f-421d-81a8-9b754d84ec52)

Click the Flying tab has nothing
![image](https://github.com/user-attachments/assets/f453c83c-30f3-4279-96b9-d4302bab2e2b)

Check the Swimming tab
![image](https://github.com/user-attachments/assets/ba59b45a-3349-435c-8a2b-b1dd88c397bc)

**Comment by DanSheps** [comment]
Can you try: /br reload?

**Comment by Brum8842** [comment]
Ok I tried that and the only thing that happened was 
![image](https://github.com/user-attachments/assets/b97e0de4-d7f3-46b5-91ed-d8fd67cde642)

but the tab is still empty
